# This workflow will build the nomads website
# Run tests - WIP 
name: Build Hugo nomads site

# Triggers the workflow on push or pull request events for the gh-pages branch
on:
  push:
    branches:
      - gh-pages
      - github-build-pipeline-init
  pull_request:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Get hugo setup
        run: |
          echo PATH $PATH
          npm init -y && npm install -y postcss-cli autoprefixer
          echo 'Install Hugo'
          HUGO_VERSION=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r '.tag_name')
          mkdir tmp/ && cd tmp/
          curl -sSL https://github.com/gohugoio/hugo/releases/download/${HUGO_VERSION}/hugo_extended_${HUGO_VERSION: -6}_Linux-64bit.tar.gz | tar -xvzf-
          mv hugo /usr/bin/
          cd .. && rm -rf tmp/
          cd ${GITHUB_WORKSPACE}
          hugo version || exit 1
      - name: Run hugo and build site
        run: |
          echo 'Clean site'
          if [ -d "public" ]; then
              rm -rf public/*
          fi

          echo 'Build site'
          hugo -d public