# This workflow will build the nomads website

name: Build Hugo nomads site

# Triggers the workflow on push or pull request events for the gh-pages branch
on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Build and deploy
        run: |
          hugo
